# Generated by Django 5.2 on 2025-05-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('form', models.CharField(max_length=100, verbose_name='Форма выпуска')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Номер партии')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество (в штуках)')),
            ],
        ),
        migrations.CreateModel(
            name='DrugMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], max_length=3, verbose_name='Тип движения')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meds.drug', verbose_name='Препарат')),
            ],
        ),
    ]
