# Generated by Django 5.2 on 2025-05-03 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_drugmovement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugmovement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
