# Generated by Django 5.2 on 2025-05-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0003_alter_drugmovement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован'),
        ),
    ]
